import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ContractProvider } from "./context";
import { AuthProvider } from "./auth/AuthProvider";
import { ThemeProvider } from "@/lib/theme-provider";
import { QueryProvider } from "./QueryProvider";
import { isProduction, isStaging } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeScript = `
(function() {
  try {
    var theme = localStorage.getItem('theme') || 'system';
    var resolved = theme === 'system'
      ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')
      : theme;
    document.documentElement.classList.remove('light', 'dark');
    document.documentElement.classList.add(resolved);
    document.documentElement.style.colorScheme = resolved;
  } catch(e) {}
})();
`;

const analyticsScript = `
(function() {
  if (window.location.hostname !== 'localhost' && window.location.hostname !== '127.0.0.1') {
    var startTime = performance.now();
    window._analyticsEndpoint = '/api/analytics';
    
    // Track page load performance
    window.addEventListener('load', function() {
      var loadTime = performance.now() - startTime;
      console.log('Page load time:', loadTime + 'ms');
      
      // Send to analytics endpoint if available
      if (window._analyticsEndpoint) {
        fetch(window._analyticsEndpoint, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            event: 'page_load',
            path: window.location.pathname,
            loadTime: loadTime,
            timestamp: new Date().toISOString()
          })
        }).catch(() => {});
      }
    });
    
    // Track errors
    window.addEventListener('error', function(event) {
      console.error('Error tracked:', event.message);
      if (window._analyticsEndpoint) {
        fetch(window._analyticsEndpoint, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            event: 'error',
            message: event.message,
            file: event.filename,
            line: event.lineno,
            col: event.colno,
            timestamp: new Date().toISOString()
          })
        }).catch(() => {});
      }
    });
  }
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        {(isProduction() || isStaging()) && (
          <script dangerouslySetInnerHTML={{ __html: analyticsScript }} />
        )}
      </head>
      <body>
        <QueryProvider>
          <ThemeProvider>
            <AuthProvider>
              <ContractProvider>
                {children}
              </ContractProvider>
            </AuthProvider>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
